Install github packages for Ubuntu or where we don't have brew/pacman/aur packages

diff --git a/.chezmoiscripts/run_onchange_02-install-tools-package.sh.tmpl b/.chezmoiscripts/run_onchange_02-install-tools-package.sh.tmpl
--- a/.chezmoiscripts/run_onchange_02-install-tools-package.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_02-install-tools-package.sh.tmpl
@@ -28,6 +28,14 @@ echo "Installing tools packages for {{ $osID }}..."
 {{- if eq $osID "arch" }}
 sudo pacman -S --needed --noconfirm {{ $packageList | trim }}
 {{- if $aurPackageList }}
+# Check if yay is installed
+if ! command -v yay &> /dev/null; then
+    echo "yay not found, installing..."
+    git clone https://aur.archlinux.org/yay.git /tmp/yay
+    (cd /tmp/yay && makepkg -si --noconfirm)
+    rm -rf /tmp/yay
+fi
+
 yay -S --needed --noconfirm {{ $aurPackageList | trim }}
 {{- end }}
 {{- else if eq $osID "darwin" }}
