Add shellcheck; dismiss wayward notifications before sunshine launches big picture; update wayward

diff --git a/chezmoi/dot_local/bin/executable_minimal-steam-big-picture-gamescope b/chezmoi/dot_local/bin/executable_minimal-steam-big-picture-gamescope
--- a/chezmoi/dot_local/bin/executable_minimal-steam-big-picture-gamescope
+++ b/chezmoi/dot_local/bin/executable_minimal-steam-big-picture-gamescope
@@ -60,6 +60,10 @@ mapfile -t OLD_IDS < <(
         jq -r '.[] | select(.app_id == "gamescope") | .id'
 )
 
+if ! wayward dismiss-notifications; then
+    echo "Could not dismiss Wayward notification popups" >&2
+fi
+
 gamescope \
     --steam \
     --grab \
